name: Build and publish

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      docker_tag_prefix:
        description: "Enter the Docker Tag Prefix (e.g adhoc-test)"
        required: true
        type: string

env:
  ECR_REPOSITORY_URL: 673156464838.dkr.ecr.us-west-2.amazonaws.com
  ECR_REPOSITORY_NAME: gpt-survey-summarizer
  DOCKER_TAG_PREFIX: ${{ github.event.inputs.docker_tag_prefix }}

jobs:
  build-and-publish:
    name: Build and Publish Docker Image
    runs-on: minafoundation-default-runners
    steps:

      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🦀 Get application version from package.json
        id: application-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: 🏷️ Generate Tag
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "TAG=${{ env.DOCKER_TAG_PREFIX }}-${{ steps.application-version.outputs.current-version }}-$SHORT_SHA" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" == "push" ] && [ -n "${{ github.event.ref }}" ]; then
            echo "TAG=${{ steps.application-version.outputs.current-version }}-$SHORT_SHA" >> $GITHUB_ENV
          else
            echo "Invalid event. Exiting..."
            exit 1
          fi

      - name: 🔑 ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: 🔍 Check if Tag already exists
        id: checktag
        uses: tyriis/docker-image-tag-exists@main
        with:
          registry: ${{ env.ECR_REPOSITORY_URL}}
          repository: ${{ env.ECR_REPOSITORY_NAME }}
          tag: ${{ env.TAG }}

      - name: 🛠️ Build and Push Docker
        uses: mr-smithers-excellent/docker-build-push@v6
        if: steps.checktag.outputs.tag == 'not found'
        with:
          image: ${{ env.ECR_REPOSITORY_NAME }}
          registry: ${{ env.ECR_REPOSITORY_URL }}
          tags: ${{ env.TAG }}
