name: Docker build

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: minafoundation-default-runners

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3
      
      - name: 🛠️ Build Docker
        # https://github.com/marketplace/actions/docker-build-push-action
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: 673156464838.dkr.ecr.us-west-2.amazonaws.com/gpt-survey-summarizer
          tags: ${{ github.ref_name }}
          registry: 673156464838.dkr.ecr.us-west-2.amazonaws.com
          pushImage: false
